apiVersion: v2
appVersion: 4.5.2
description: Responsible for regenerating auth-keys per x hours
home: https://gluu.org/docs/gluu-server
icon: https://gluu.org/docs/gluu-server/favicon.ico
keywords:
- Auth keys Rotation
kubeVersion: '>=v1.21.0-0'
maintainers:
- email: support@gluu.org
  name: Mohammad Abudayyeh
  url: https://github.com/moabu
name: oxauth-key-rotation
sources:
- https://github.com/GluuFederation/docker-certmanager
- https://github.com/GluuFederation/cloud-native-edition/tree/4.3/pygluu/kubernetes/templates/helm/gluu/charts/oxauth-key-rotationn
type: application
version: 1.8.0
