apiVersion: v2
appVersion: 4.5.2
description: Configuration parameters for setup and initial configuration secret and
  config layers used by Gluu services.
home: https://gluu.org/docs/gluu-server/reference/container-configs/
icon: https://gluu.org/docs/gluu-server/favicon.ico
keywords:
- configuration
- secrets
kubeVersion: '>=v1.21.0-0'
maintainers:
- email: support@gluu.org
  name: Mohammad Abudayyeh
  url: https://github.com/moabu
name: config
sources:
- https://gluu.org/docs/gluu-server/reference/container-configs/
- https://github.com/GluuFederation/docker-config-init
- https://github.com/GluuFederation/cloud-native-edition/tree/4.4/pygluu/kubernetes/templates/helm/gluu/charts/config
type: application
version: 1.8.23
