apiVersion: v2
appVersion: 4.5.2
description: Middleware API to help application developers call an OAuth, OpenID or
  UMA server. You may wonder why this is necessary. It makes it easier for client
  developers to use OpenID signing and encryption features, without becoming crypto
  experts. This API provides some high level endpoints to do some of the heavy lifting.
home: https://gluu.org/docs/oxd
icon: https://gluu.org/docs/gluu-server/favicon.ico
keywords:
- OXD
- API
kubeVersion: '>=v1.21.0-0'
maintainers:
- email: support@gluu.org
  name: Mohammad Abudayyeh
  url: https://github.com/moabu
name: oxd-server
sources:
- https://github.com/GluuFederation/docker-oxd
- https://github.com/GluuFederation/cloud-native-edition/tree/4.3/pygluu/kubernetes/templates/helm/gluu/charts/oxd-server
type: application
version: 1.8.23
