apiVersion: v2
appVersion: 4.5.2
description: OAuth Authorization Server, the OpenID Connect Provider, the UMA Authorization
  Server--this is the main Internet facing component of Gluu. It's the service that
  returns tokens, JWT's and identity assertions. This service must be Internet facing.
home: https://gluu.org/docs/gluu-server
icon: https://gluu.org/docs/gluu-server/favicon.ico
keywords:
- Autherization
- OpenID
kubeVersion: '>=v1.21.0-0'
maintainers:
- email: support@gluu.org
  name: Mohammad Abudayyeh
  url: https://github.com/moabu
name: oxauth
sources:
- https://github.com/GluuFederation/docker-oxauth
- https://github.com/GluuFederation/cloud-native-edition/tree/4.3/pygluu/kubernetes/templates/helm/gluu/charts/oxauth
type: application
version: 1.8.23
