apiVersion: v2
appVersion: 4.5.2
description: System for Cross-domain Identity Management (SCIM) version 2.0
home: https://gluu.org/docs/gluu-server
icon: https://gluu.org/docs/gluu-server/favicon.ico
keywords:
- SCIM
- API
kubeVersion: '>=v1.21.0-0'
maintainers:
- email: support@gluu.org
  name: Mohammad Abudayyeh
  url: https://github.com/moabu
name: scim
sources:
- https://gluu.org/docs/gluu-server/api-guide/scim-api/
- https://github.com/GluuFederation/docker-scim
- https://github.com/GluuFederation/cloud-native-edition/tree/4.4/pygluu/kubernetes/templates/helm/gluu/charts/scim
type: application
version: 1.8.23
