apiVersion: v2
appVersion: 4.5.2
description: FIDO 2.0 (FIDO2) is an open authentication standard that enables leveraging
  common devices to authenticate to online services in both mobile and desktop environments.
home: https://gluu.org/docs/gluu-server/
icon: https://gluu.org/docs/gluu-server/favicon.ico
keywords:
- fido2
- u2f
kubeVersion: '>=v1.21.0-0'
maintainers:
- email: support@gluu.org
  name: Mohammad Abudayyeh
  url: https://github.com/moabu
name: fido2
sources:
- https://gluu.org/docs/gluu-server/
- https://github.com/GluuFederation/docker-fido2
- https://github.com/GluuFederation/cloud-native-edition/tree/4.4/pygluu/kubernetes/templates/helm/gluu/charts/fido2
type: application
version: 1.8.23
