apiVersion: v2
appVersion: 4.5.2
description: Job to generate data and initial config for Gluu Server persistence layer.
home: https://gluu.org/docs/gluu-server
icon: https://gluu.org/docs/gluu-server/favicon.ico
keywords:
- persistence prep
kubeVersion: '>=v1.21.0-0'
maintainers:
- email: support@gluu.org
  name: Mohammad Abudayyeh
  url: https://github.com/moabu
name: persistence
sources:
- https://github.com/GluuFederation/docker-persistence
- https://github.com/GluuFederation/cloud-native-edition/tree/4.4/pygluu/kubernetes/templates/helm/gluu/charts/persistence
type: application
version: 1.8.23
